# .bwmachined.conf
# Format: BW_ROOT;BW_RES_PATH[:BW_RES_PATH]...
# BW_ROOT = 服务器二进制根目录
# BW_RES_PATH = 资源路径（冒号分隔）
/home/great/bw-build/game/bin/server/el7;/home/great/bw-build/programming/bigworld/examples/client_integration/python/simple/res
